import type {
  AdaptiveTuning,
  FilterPresetDefinition,
  HslBandAdjustment,
} from "../filter-engine/types";

const adaptiveDefaults: AdaptiveTuning = {
  portraitProtection: 0.72,
  saturationGuard: 0.68,
  highlightRecovery: 0.7,
  shadowSafety: 0.64,
  lowLightRestraint: 0.68,
  indoorCorrection: 0.55,
  outdoorModeration: 0.5,
};

const orangeSkinProtection: HslBandAdjustment = {
  label: "Skin",
  minHue: 16,
  maxHue: 52,
  hueShift: -2,
  saturation: -4,
  lightness: 4,
  softness: 22,
};

const foliageSoftening: HslBandAdjustment = {
  label: "Greens",
  minHue: 82,
  maxHue: 150,
  hueShift: -4,
  saturation: -10,
  lightness: 4,
  softness: 18,
};

export const FILTER_PRESETS: FilterPresetDefinition[] = [
  {
    id: "original",
    name: "Original",
    category: "Core",
    mood: "Unedited reference",
    description: "No grading. Use it as the neutral base for comparison and custom work.",
    whyItWorks: "It preserves the source image exactly so every preset and manual adjustment has a trustworthy baseline.",
    defaultStrength: 1,
    tags: ["neutral", "reference"],
    adjustments: {},
    adaptive: adaptiveDefaults,
    sceneAffinity: {},
  },
  {
    id: "minimal-rich",
    name: "Minimal Rich",
    category: "Premium Clean",
    mood: "Quiet luxury with depth",
    description: "Neutral, polished, and slightly dimensional without looking processed.",
    whyItWorks: "A restrained S-curve, lifted shadows, and mild color discipline keep textures rich while avoiding a preset-overlay look.",
    defaultStrength: 0.88,
    tags: ["clean", "editorial", "premium"],
    adjustments: {
      brightness: 4,
      contrast: 10,
      highlights: -10,
      shadows: 12,
      whites: 8,
      blacks: 4,
      saturation: -4,
      vibrance: 8,
      clarity: 8,
      sharpness: 6,
      vignette: 6,
    },
    curve: {
      master: [4, 56, 128, 206, 249],
      b: [2, 58, 130, 206, 247],
    },
    hsl: [orangeSkinProtection, foliageSoftening],
    adaptive: { ...adaptiveDefaults, portraitProtection: 0.8 },
    sceneAffinity: { portrait: 0.7, food: 0.8, lifestyle: 0.75, indoor: 0.45, outdoor: 0.55 },
  },
  {
    id: "aesthetic-soft",
    name: "Aesthetic Soft",
    category: "Soft Light",
    mood: "Gentle pastel editorial",
    description: "Bright, diffused, and softly romantic with restrained color lift.",
    whyItWorks: "Lower contrast, subtle bloom, and softened micro-contrast create softness without flattening skin tones.",
    defaultStrength: 0.84,
    tags: ["soft", "airy", "social"],
    adjustments: {
      brightness: 8,
      contrast: -10,
      highlights: -12,
      shadows: 14,
      whites: 10,
      blacks: 8,
      saturation: -6,
      vibrance: 10,
      temperature: 6,
      tint: 4,
      clarity: -10,
      sharpness: -8,
      bloom: 14,
      fade: 8,
      vignette: 4,
    },
    curve: {
      master: [10, 60, 132, 214, 248],
      r: [12, 64, 136, 218, 250],
    },
    splitTone: {
      balance: 8,
      shadows: { hue: 225, saturation: 6 },
      highlights: { hue: 34, saturation: 8 },
    },
    hsl: [
      { ...orangeSkinProtection, saturation: -6, lightness: 6 },
      { label: "Blues", minHue: 180, maxHue: 255, hueShift: 6, saturation: -12, lightness: 8, softness: 20 },
    ],
    adaptive: { ...adaptiveDefaults, lowLightRestraint: 0.82, portraitProtection: 0.86 },
    sceneAffinity: { portrait: 0.9, lifestyle: 0.72, bright: 0.55, indoor: 0.5, flat: 0.48 },
  },
  {
    id: "clean-luxury",
    name: "Clean Luxury",
    category: "Premium Clean",
    mood: "Refined commercial polish",
    description: "Crisp whites, disciplined color, and expensive-looking neutrality.",
    whyItWorks: "It boosts separation in highlights and texture while trimming cheap saturation, which keeps product, fashion, and interiors premium.",
    defaultStrength: 0.9,
    tags: ["commercial", "clean", "luxury"],
    adjustments: {
      brightness: 6,
      contrast: 6,
      highlights: -18,
      shadows: 8,
      whites: 12,
      blacks: 4,
      saturation: -10,
      vibrance: 8,
      temperature: -4,
      tint: 2,
      clarity: 10,
      sharpness: 10,
      vignette: 8,
    },
    curve: {
      master: [2, 52, 128, 214, 252],
      g: [4, 54, 130, 214, 249],
    },
    hsl: [
      { ...orangeSkinProtection, saturation: -2, lightness: 5 },
      { label: "Yellows", minHue: 45, maxHue: 78, hueShift: -8, saturation: -14, lightness: 4, softness: 16 },
    ],
    adaptive: { ...adaptiveDefaults, highlightRecovery: 0.9, indoorCorrection: 0.72 },
    sceneAffinity: { food: 0.72, indoor: 0.8, lifestyle: 0.72, portrait: 0.62, bright: 0.46 },
  },
  {
    id: "cinematic-mood",
    name: "Cinematic Mood",
    category: "Cinematic",
    mood: "Teal-shadow drama with controlled warmth",
    description: "Deepens atmosphere while keeping highlights believable and skin from turning orange.",
    whyItWorks: "Color separation between cool shadows and warm highs adds cinematic depth without aggressive global tinting.",
    defaultStrength: 0.86,
    tags: ["cinematic", "moody", "story"],
    adjustments: {
      brightness: -8,
      contrast: 18,
      highlights: -20,
      shadows: -10,
      whites: -4,
      blacks: -8,
      saturation: -8,
      vibrance: 8,
      temperature: -4,
      tint: 3,
      clarity: 12,
      sharpness: 8,
      grain: 10,
      vignette: 18,
      bloom: 6,
    },
    curve: {
      master: [0, 42, 120, 202, 246],
      b: [10, 58, 132, 210, 248],
      r: [0, 38, 118, 205, 250],
    },
    splitTone: {
      balance: -12,
      shadows: { hue: 205, saturation: 16 },
      highlights: { hue: 36, saturation: 10 },
    },
    hsl: [
      { ...orangeSkinProtection, saturation: -3, lightness: 2 },
      { label: "Cyans", minHue: 170, maxHue: 230, hueShift: -8, saturation: 12, lightness: -6, softness: 24 },
    ],
    adaptive: { ...adaptiveDefaults, highlightRecovery: 0.84, outdoorModeration: 0.7 },
    sceneAffinity: { street: 0.88, lowLight: 0.76, outdoor: 0.6, indoor: 0.56, portrait: 0.42 },
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    category: "Warm Glow",
    mood: "Sunlit warmth without yellow overload",
    description: "Adds sunset warmth, subtle softness, and luminous highlights that still hold detail.",
    whyItWorks: "Warmth is pushed mostly into the highs and oranges, while adaptive controls keep already-warm scenes from turning muddy.",
    defaultStrength: 0.84,
    tags: ["warm", "sunset", "lifestyle"],
    adjustments: {
      brightness: 8,
      contrast: 4,
      highlights: -12,
      shadows: 10,
      whites: 8,
      blacks: 2,
      saturation: 4,
      vibrance: 12,
      temperature: 18,
      tint: 4,
      clarity: 2,
      bloom: 12,
      fade: 5,
      vignette: 8,
    },
    curve: {
      master: [4, 50, 128, 210, 250],
      r: [8, 58, 136, 220, 252],
      b: [0, 44, 122, 198, 242],
    },
    splitTone: {
      balance: 18,
      shadows: { hue: 215, saturation: 8 },
      highlights: { hue: 34, saturation: 16 },
    },
    hsl: [
      { ...orangeSkinProtection, saturation: 4, lightness: 4 },
      { label: "Yellows", minHue: 42, maxHue: 74, hueShift: -6, saturation: 8, lightness: 6, softness: 18 },
    ],
    adaptive: { ...adaptiveDefaults, outdoorModeration: 0.78, saturationGuard: 0.82 },
    sceneAffinity: { outdoor: 0.88, portrait: 0.76, lifestyle: 0.82, bright: 0.66, food: 0.4 },
  },
  {
    id: "vintage-film",
    name: "Vintage Film",
    category: "Film",
    mood: "Warm nostalgia with tactile grain",
    description: "Subtle fade, softer contrast, and film-like warmth for timeless social imagery.",
    whyItWorks: "A lifted toe and warm channel bias make the image feel analog while controlled saturation prevents the look from feeling gimmicky.",
    defaultStrength: 0.82,
    tags: ["film", "nostalgic", "grain"],
    adjustments: {
      brightness: 2,
      contrast: -8,
      highlights: -10,
      shadows: 12,
      whites: 6,
      blacks: 10,
      saturation: -8,
      vibrance: 4,
      temperature: 12,
      tint: 2,
      clarity: -4,
      sharpness: -2,
      fade: 16,
      grain: 18,
      vignette: 8,
    },
    curve: {
      master: [16, 60, 128, 198, 238],
      r: [18, 64, 132, 204, 244],
      b: [10, 52, 124, 192, 232],
    },
    splitTone: {
      balance: 10,
      shadows: { hue: 198, saturation: 6 },
      highlights: { hue: 40, saturation: 10 },
    },
    hsl: [orangeSkinProtection],
    adaptive: { ...adaptiveDefaults, lowLightRestraint: 0.82, saturationGuard: 0.8 },
    sceneAffinity: { lifestyle: 0.84, street: 0.7, portrait: 0.62, outdoor: 0.56, flat: 0.35 },
  },
  {
    id: "matte-editorial",
    name: "Matte Editorial",
    category: "Editorial",
    mood: "Matte magazine finish",
    description: "Flattened toe, soft highlight roll-off, and poised color restraint.",
    whyItWorks: "It lifts blacks intentionally while keeping midtones articulate, which gives a fashion-editorial finish instead of a washed-out one.",
    defaultStrength: 0.86,
    tags: ["matte", "editorial", "fashion"],
    adjustments: {
      brightness: 4,
      contrast: -12,
      highlights: -8,
      shadows: 10,
      whites: 4,
      blacks: 18,
      saturation: -10,
      vibrance: 2,
      temperature: -2,
      clarity: 8,
      sharpness: 4,
      fade: 18,
      grain: 10,
      vignette: 12,
    },
    curve: {
      master: [24, 70, 132, 202, 240],
      g: [18, 68, 130, 202, 238],
    },
    splitTone: {
      balance: -4,
      shadows: { hue: 214, saturation: 8 },
      highlights: { hue: 32, saturation: 6 },
    },
    hsl: [
      { ...orangeSkinProtection, saturation: -6, lightness: 5 },
      foliageSoftening,
    ],
    adaptive: { ...adaptiveDefaults, portraitProtection: 0.82, indoorCorrection: 0.62 },
    sceneAffinity: { portrait: 0.72, indoor: 0.66, lifestyle: 0.74, flat: 0.52, street: 0.44 },
  },
  {
    id: "bright-airy",
    name: "Bright Airy",
    category: "Soft Light",
    mood: "High-key daylight polish",
    description: "Raises exposure feel, softens contrast, and keeps whites clean and breathable.",
    whyItWorks: "Highlight recovery and low-contrast shaping make bright scenes feel luxurious rather than blown out.",
    defaultStrength: 0.88,
    tags: ["airy", "bright", "clean"],
    adjustments: {
      brightness: 14,
      contrast: -10,
      highlights: -18,
      shadows: 12,
      whites: 14,
      blacks: 10,
      saturation: -6,
      vibrance: 8,
      temperature: 4,
      tint: 2,
      clarity: -6,
      sharpness: -4,
      bloom: 10,
      fade: 8,
      vignette: 4,
    },
    curve: {
      master: [12, 68, 138, 220, 252],
      g: [14, 70, 140, 222, 252],
    },
    hsl: [
      { ...orangeSkinProtection, saturation: -2, lightness: 6 },
      { label: "Blues", minHue: 180, maxHue: 240, hueShift: 2, saturation: -10, lightness: 10, softness: 18 },
    ],
    adaptive: { ...adaptiveDefaults, highlightRecovery: 0.92, lowLightRestraint: 0.86 },
    sceneAffinity: { bright: 0.94, portrait: 0.7, indoor: 0.46, outdoor: 0.78, overexposed: 0.58 },
  },
  {
    id: "moody-cool",
    name: "Moody Cool",
    category: "Cinematic",
    mood: "Cool, polished atmosphere",
    description: "Leans blue-cool, deepens mood, and keeps the frame elegant instead of muddy.",
    whyItWorks: "Contrast, cool temperature, and shadow shaping are balanced with highlight protection so the image stays expensive-looking.",
    defaultStrength: 0.86,
    tags: ["cool", "mood", "night"],
    adjustments: {
      brightness: -6,
      contrast: 14,
      highlights: -18,
      shadows: -4,
      whites: -2,
      blacks: -8,
      saturation: -8,
      vibrance: 6,
      temperature: -14,
      tint: 2,
      clarity: 12,
      sharpness: 8,
      grain: 8,
      vignette: 16,
    },
    curve: {
      master: [2, 40, 120, 204, 244],
      b: [10, 56, 132, 214, 250],
    },
    splitTone: {
      balance: -16,
      shadows: { hue: 212, saturation: 14 },
      highlights: { hue: 218, saturation: 6 },
    },
    hsl: [
      { ...orangeSkinProtection, saturation: -4, lightness: 3 },
      { label: "Blues", minHue: 185, maxHue: 245, hueShift: -6, saturation: 12, lightness: -4, softness: 20 },
    ],
    adaptive: { ...adaptiveDefaults, lowLightRestraint: 0.8, outdoorModeration: 0.72 },
    sceneAffinity: { street: 0.82, lowLight: 0.72, indoor: 0.58, outdoor: 0.44, portrait: 0.38 },
  },
  {
    id: "night-pop",
    name: "Night Pop",
    category: "Night",
    mood: "Urban neon clarity",
    description: "Designed for city nights, signage, interiors, and scenes that need extra separation without clipping light sources.",
    whyItWorks: "It selectively boosts detail and vibrance while scene-aware restraint holds bloom, grain, and highlights in difficult low-light files.",
    defaultStrength: 0.9,
    tags: ["night", "neon", "urban"],
    adjustments: {
      brightness: -2,
      contrast: 20,
      highlights: -12,
      shadows: 2,
      whites: 8,
      blacks: -10,
      saturation: 6,
      vibrance: 18,
      temperature: -8,
      tint: 4,
      clarity: 20,
      sharpness: 18,
      bloom: 10,
      grain: 12,
      vignette: 18,
    },
    curve: {
      master: [0, 36, 120, 210, 248],
      b: [8, 48, 132, 218, 252],
      r: [2, 38, 118, 206, 246],
    },
    splitTone: {
      balance: -8,
      shadows: { hue: 220, saturation: 18 },
      highlights: { hue: 320, saturation: 8 },
    },
    hsl: [
      { label: "Magentas", minHue: 285, maxHue: 340, hueShift: -4, saturation: 16, lightness: 2, softness: 20 },
      { label: "Cyans", minHue: 180, maxHue: 230, hueShift: -4, saturation: 12, lightness: 4, softness: 20 },
    ],
    adaptive: { ...adaptiveDefaults, lowLightRestraint: 0.92, highlightRecovery: 0.82, saturationGuard: 0.76 },
    sceneAffinity: { lowLight: 0.96, street: 0.82, indoor: 0.72, colorful: 0.64, underexposed: 0.48 },
  },
  {
    id: "soft-portrait",
    name: "Soft Portrait",
    category: "Portrait",
    mood: "Natural skin-first polish",
    description: "Prioritizes flattering skin, mild warmth, and gentle softness while keeping eyes and edges believable.",
    whyItWorks: "Skin hues are explicitly protected while contrast and detail are softened just enough to flatter without smearing the whole frame.",
    defaultStrength: 0.88,
    tags: ["portrait", "skin", "soft"],
    adjustments: {
      brightness: 8,
      contrast: -6,
      highlights: -18,
      shadows: 10,
      whites: 8,
      blacks: 8,
      saturation: -6,
      vibrance: 10,
      temperature: 6,
      tint: 5,
      clarity: -8,
      sharpness: -6,
      bloom: 12,
      vignette: 6,
    },
    curve: {
      master: [8, 62, 136, 214, 248],
      r: [10, 66, 140, 218, 250],
    },
    splitTone: {
      balance: 12,
      shadows: { hue: 220, saturation: 4 },
      highlights: { hue: 34, saturation: 8 },
    },
    hsl: [
      { ...orangeSkinProtection, hueShift: -1, saturation: -8, lightness: 8, softness: 26 },
      { label: "Reds", minHue: 350, maxHue: 20, hueShift: -2, saturation: -4, lightness: 4, softness: 20 },
    ],
    adaptive: { ...adaptiveDefaults, portraitProtection: 0.98, saturationGuard: 0.82, lowLightRestraint: 0.84 },
    sceneAffinity: { portrait: 0.98, lifestyle: 0.8, indoor: 0.66, bright: 0.44, flat: 0.42 },
  },
  {
    id: "monochrome-premium",
    name: "Monochrome Premium",
    category: "Black & White",
    mood: "High-end monochrome contrast",
    description: "Rich black and white with controlled highlight roll-off and enough grain to feel tactile.",
    whyItWorks: "A neutral monochrome conversion plus tonal shaping avoids muddy grays and keeps faces, fabrics, and architecture premium.",
    defaultStrength: 0.92,
    tags: ["bw", "monochrome", "premium"],
    adjustments: {
      brightness: 2,
      contrast: 22,
      highlights: -10,
      shadows: 6,
      whites: 10,
      blacks: -10,
      saturation: -100,
      vibrance: -100,
      clarity: 14,
      sharpness: 12,
      grain: 18,
      vignette: 14,
      fade: 4,
    },
    curve: {
      master: [2, 42, 124, 214, 250],
    },
    adaptive: { ...adaptiveDefaults, highlightRecovery: 0.86, shadowSafety: 0.72 },
    sceneAffinity: { street: 0.82, portrait: 0.68, lowLight: 0.44, indoor: 0.5, flat: 0.52 },
  },
];

export const presetByName = new Map(FILTER_PRESETS.map((preset) => [preset.name, preset]));
export const presetById = new Map(FILTER_PRESETS.map((preset) => [preset.id, preset]));

export function getFilterPreset(filterName: string): FilterPresetDefinition {
  return presetByName.get(filterName) ?? FILTER_PRESETS[0];
}

export function getFilterPresetById(presetId: string): FilterPresetDefinition {
  return presetById.get(presetId) ?? FILTER_PRESETS[0];
}
